FROM php:7.4-fpm

COPY ./php.ini /etc/php/conf.d/php.ini
RUN chmod 644 /etc/php/conf.d/php.ini

RUN apt update && apt install -y git zip unzip vim libonig-dev libzip-dev libxml2-dev libgd-dev
RUN docker-php-ext-install pdo_mysql mbstring zip xml gd mysqli

WORKDIR /var/www/html
