version: '3'

services:

    php:
        container_name: php
        user: $user
        build: ./php/
        volumes:
            - ../php:/var/www/html/

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf/:/etc/nginx/conf.d/default.conf
            - ../php/public/:/var/www/html/

    db:
        image: mysql:5.7
        image: mysql/mysql-server:8.0
        container_name: db
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_USER: test_user
            MYSQL_PASSWORD: test_ps
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo"
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
