version: '3'

services:

    php:
        container_name: php
        user: $user
        build: ./php/
        volumes:
            - ../php:/var/www/html/
        depends_on:
            - db

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf/:/etc/nginx/conf.d/default.conf
            - ../nginx/:/var/www/html/
        depends_on:
            - php

    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo"
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
